In [ ]:
#Nama: I Made Suastika
#NIM : 1708561001

In [1]:
# mengaktifkan package pandas dan numpy yang akan digunakan pada tahapan analisis.
#Package pandas sendiri digunakan untuk pengolahan data yang berkaitan dengan data frame. 
#sedangkan package numpy digunakan untuk manipulasi array secara mudah dan cepat.

import numpy as np
import pandas as pd

In [2]:
# input data
data=pd.read_excel("data.xlsx")

# menampilkan data, hanya beberapa data saja yang ditampilkan  
data.head()

Pelamar  IPK  Psikologi  Wawancara  Diterima
0        1    2          2          1         1
1        2    2          1          1         1
2        3    2          1          0         1
3        4    2          2          0         0
4        5    1          3          1         1

In [3]:
# menampilkan info setiap variabel
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Pelamar    11 non-null     int64
 1   IPK        11 non-null     int64
 2   Psikologi  11 non-null     int64
 3   Wawancara  11 non-null     int64
 4   Diterima   11 non-null     int64
dtypes: int64(5)
memory usage: 568.0 bytes


In [4]:
#menentukan variabel, disini ada 5 buah variabel yaitu: pelamar, IPK, Psikologi, Wawancara dan Diterima

# variavle independen: Pelamar, IPK, Psikologi dan Wawancara
x=data.drop(["Diterima"], axis = 1)

#variabel dependen: Diterima
y=data["Diterima"]

In [5]:
#memanggil klasifikasi naive Bayes dalam package Skelearn dan melakukan proses training data, dengan random state nya adalah 123.

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

#menampilkan data testing variabel independen
x_test

Pelamar  IPK  Psikologi  Wawancara
0        1    2          2          1
4        5    1          3          1
5        6    1          1          1

In [6]:
#mengaktifkan fungsi klasifikasi naive bayes dan memasukkan data training pada fungsi klasifikasi

from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([3., 5.])

In [7]:
#menentukan hasil prediksi data testing

y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1], dtype=int64)

In [8]:
#nilai testing yang sebenarnya

np.array(y_test)

array([1, 1, 1], dtype=int64)

In [9]:
#mencari nilai probabilitas dari hasil prediksi

nbtrain.predict_proba(x_test)

array([[0., 1.],
       [0., 1.],
       [0., 1.]])

In [10]:
#Membuat confusion matriks

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3]], dtype=int64)

In [11]:
#menampilkan nilai akurasi

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         3

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

